[package]
name = "rust-mod"
version = "0.1.0"
authors = ["LastLeaf <bqfu@163.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.71"
js-sys = "0.3.48"
md5 = "0.7.0"

[profile.release]
opt-level = "s"
lto = true
